### ISSUE TITLE
Php version

### ISSUE THREAD

**Issue by wmdhosting** [ryssbowh/craft-emails#1]
This plugin requires PHP >=7.4, but your environment is currently running 7.4.27.  

is this some bug..  in store.,.
![Snag_120433ff](https://user-images.githubusercontent.com/76176291/149986895-455595e9-94a3-4320-9969-f351633c956f.png)

**Comment by ryssbowh** [comment]
This is strange indeed, I have 7.4.24 and I don't see that message

**Comment by ryssbowh** [comment]
Do you have access to a terminal ?
You could try manually : `composer install ryssbowh/craft-emails`

**Comment by wmdhosting** [comment]
yes i have installed  manually..   thx
