### ISSUE TITLE
Adding images within redactor field

### ISSUE THREAD

**Issue by mitchellgemma** [ryssbowh/craft-emails#11]
**Describe the bug**
I am trying to add an image within the redactor field, but it does not load or allow me to upload any images. It's working perfectly in my redactor fields for normal entries.

**To Reproduce**
1. Create new email
2. Add content to email
3. Try to add an image within redactor field

**Software:**
 - Emails version: 2.0.8
 - Craft version: 4.4.1
 - Email adaptor (sendgrid etc): SMTP

<img width="1910" alt="Screen Shot 2023-03-13 at 11 34 56 AM" src="https://user-images.githubusercontent.com/107566585/224750640-ea46cbbd-4e65-4261-9600-67b91f3d53e2.png">

**Comment by ryssbowh** [comment]
Thanks for reporting, I've fixed this in 2.0.9.

**Comment by mitchellgemma** [comment]
Thank you!
