### ISSUE TITLE
All emails being marked as spam

### ISSUE THREAD

**Issue by mitchellgemma** [ryssbowh/craft-emails#12]
**Describe the bug**
When sending an email shot, all emails are being marked as spam. I've tried sending emails not related to the plugin and those sent with no issues. It was working for me. I was sending a fair amount of emails for testing purposes. I also tried creating and new email and email shot. In my logs I am receiving the error message:

`2023-03-15 15:38:47 [queue.INFO] [Ryssbowh\CraftEmails\services\EmailerService::_send] Sending email "Hello World" to "EMAIL@gmail.com" {"memory":7807144} 
2023-03-15 15:38:47 [queue.ERROR] [yii\symfonymailer\Mailer::sendMessage] Expected response code "250" but got code "550", with message "550 5.7.1 Message detected as spam. [1678894726-342487].". {"memory":7925960}  `

**To Reproduce**
1. Send test emails
2. Eventually emails stop sending and receive error message in logs

**Software:**
 - Emails version: 2.0.9
 - Craft version: 4.4.1
 - Email adaptor (sendgrid etc): SMTP

**Comment by ryssbowh** [comment]
Hi, may I ask more info :
- what is your smtp server ?
- how many emails do you send at once ?

**Comment by mitchellgemma** [comment]
Hello,

- our SMTP server is using [mail.enom.com](url)
- I am only sending 2 emails at once

Thanks!

**Comment by ryssbowh** [comment]
Hi,

You're getting the error 550 5.7.1 which i'm reading [here](https://www.enginemailer.com/blog/email-error-550-what-is-it-and-how-to-fix-it) means :

> This error message means the email was rejected either because of security policies or incorrect configuration on the recipient side.

If you're sending to EMAIL@gmail.com it makes sense as this doesn't seem to be a valid email ? Have you tried with other recipients ?

**Comment by mitchellgemma** [comment]
Yes I've tried with other recipients, EMAIL@gmail.com was just a placeholder for all of the other emails that I had tried. I tried sending emails in my staging environment, and it seems to be working fine, so it could possibly be something wrong with my local environment.

**Comment by mitchellgemma** [comment]
Reopening this issue as it continues to be an issue - I continue to receive the same error message and all emails are still being blocked. All other email functionality on the site works with no issues, so it does not seem to be an issue with our smtp server. Every few days it allows for emails to be sent, but then goes back to blocking everything as spam. Thanks in advance for your help!

**Comment by ryssbowh** [comment]
Hi,

Are you still getting those 550 errors ? does that happen on all environments (local, dev, staging, production) ?

This is definitely coming from your smtp server, have you contacted them to ask about the issue ?
If they can pinpoint what the issue is I'm happy to do whatever changes need done on the plugin but without their feedback there's nothing I can do really.
