### ISSUE TITLE
'No target destination provided for uploading' when uploading file

### ISSUE THREAD

**Issue by mitchellgemma** [ryssbowh/craft-emails#13]
**Describe the bug**

When uploading files directly to the email (see screenshot) Craft returns an error message, 'No target destination provided for uploading'. Wondering if I have to specify which volume to upload files to? I couldn't find anything in the documentation or within Craft.

<img width="1691" alt="Screen Shot 2023-04-13 at 9 52 48 AM" src="https://user-images.githubusercontent.com/107566585/231781874-2416ff2c-0d8d-47a4-81d7-27cdbe3d3b11.png">

**To Reproduce**
1. Create email
2. Upload file within email

**Software:**
 - Emails version: 2.0.9
 - Craft version: 4.4.1
 - Email adaptor (sendgrid etc): SMTP

**Comment by ryssbowh** [comment]
Hm yes, that should have been disabled, an upload would require a field but we don't have any here.
You can still upload an asset once the modal is open though.
This is out in 2.0.10

**Comment by mitchellgemma** [comment]
Thank you!
