### ISSUE TITLE
Error during installation – TypeError with ksort

### ISSUE THREAD

**Issue by MoritzLost** [ryssbowh/craft-emails#15]
**Describe the bug**

I'm getting an error when trying to install the plugin in a development environment. This error occurs after all the migrations have run successfully:

![Screenshot 2023-06-20 at 15 33 10](https://github.com/ryssbowh/craft-emails/assets/10146880/4ef3ada5-dd49-43b0-b961-d1ab23b2dfad)

Relevant logs entry:

> 2023-06-20 13:30:27 [web.ERROR] [craft\controllers\BaseUpdaterController::installPlugin] Plugin installation failed: ksort(): Argument #1 ($array) must be of type array, null given {"memory":9533528} 

I could be wrong, but looks like it's coming from the `Settings` model?

https://github.com/ryssbowh/craft-emails/blob/master/src/models/Settings.php#L49

We don't have Redactor installed, so `$options` will be `null` there.

**To Reproduce**

1. Try to install the plugin on a site _without_ the Redactor plugin.

**Software:**
 - Emails version: 2.0.10
 - Craft version: 4.4.13
 - Email adaptor (sendgrid etc): SMTP

**Comment by ryssbowh** [comment]
The redactor plugin would be installed automatically, it's used to write html emails.
I've fixed this error on 2.0.11, so it's installable but you won't be able to create emails without at least one redactor config file

**Comment by MoritzLost** [comment]
@ryssbowh Thanks for the quick resolution! I'll give that a shot later today.

Given that Redactor will [reach its end of life in six months](https://imperavi.com/redactor/) and [Craft now recommends CKEditor](https://craftcms.com/blog/ckeditor-revamped), are there plans to switch to CKEditor for this plugin? Or maybe support different WYSIWYG fields, or even just have an option to only use plain-text fields?

**Comment by MoritzLost** [comment]
@ryssbowh The fix works, thanks! I can now install the plugin normally, though as you said, I can't create any emails without having at least one Redactor config. I'm closing this issue as the error is resolved. That said, having the plugin work with other WYSIWYG editors or fallback to plaintext would be a great addition.

**Comment by theurbanu** [comment]
> Given that Redactor will [reach its end of life in six months](https://imperavi.com/redactor/) and [Craft now recommends CKEditor](https://craftcms.com/blog/ckeditor-revamped), are there plans to switch to CKEditor for this plugin? Or maybe support different WYSIWYG fields, or even just have an option to only use plain-text fields?

Any word on this?

**Comment by ryssbowh** [comment]
Yes CKEditor will be supported, will probably make it up to the user to select which whey want to use and disable the html fields if none is selected

**Comment by ryssbowh** [comment]
CKEditor support is out in 2.1.0 and 1.5.0.
The Wygiwys editor is now chosen in the config and it's up to you which you want to install.
Note that if you didn't have Redactor required in your composer.json you will need to require it manually, the plugin doesn't require it anymore
