### ISSUE TITLE
 Error sending email: Undefined index:

### ISSUE THREAD

**Issue by xsinisa** [ryssbowh/craft-emails#2]
Hi,

I am getting this error

2022-01-18 22:04:08 [-][-][-][warning][application] Error sending email: Undefined index:

I am using sendgrid.

**Comment by ryssbowh** [comment]
Hi,

Would you have more info ? any logs ? what Craft version are you using ?

**Comment by xsinisa** [comment]
Craft version and everything else is up to date and this is only relevant in web.log
2022-01-18 22:04:08 [-][-][-][warning][application] Error sending email: Undefined index:

Nothing in phperror log created by Craft and nothing in system php error log.

**Comment by ryssbowh** [comment]
Have been trying to open a Sendgrid account but they won't let me without a genuine business setup it seems. I've tried several other services without issue.

If you wished to share you API key privately I could use that to fix this issue ?

**Comment by xsinisa** [comment]
Unfortunately I cant share the key...but the business setup is really trivial, use dummy data.
But definitely the problem is only with sendgrid, sendmail works great.

**Comment by ryssbowh** [comment]
Actually this was a wider issue with the reply to email being set when undefined.
Fixed in 1.2.5

**Comment by xsinisa** [comment]
Thank you.
