### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by DaAnEr80** [ryssbowh/craft-emails#4]
By reading thru the documentation I could not find information on how to inset variables in an email template. I want to be able to send an email that includes userdata from the user that receives the mail, like name, phone and other related user data. 

I have tried to use the variable {{user}} but it dont work. Is it possible to do this?

**Comment by ryssbowh** [comment]
You'll have access to the default variables set by Craft such as `currentUser` for example.

If this is a manual email you can set your variables when creating it :
```
Craft::$app->getMailer()
    ->composeFromKey('email_key', [
        'var1' => 'value1', 
        'val2' => 'value2'
    ])
    ->setTo($user)
    ->send();

```
