### ISSUE TITLE
Cannot Install - con_emails table

### ISSUE THREAD

**Issue by beckbailey** [ryssbowh/craft-emails#5]
**Describe the bug**

I cannot install Craft Emails using the Plugin Store or through Composer.

**To Reproduce**
1. Install Craft Emails through Composer or Plugin Store, Error Below Occurs
2.
3.

**Software:**
 - Emails version: 1.4.1
 - Craft version: 3.7.44
 - Email adaptor (sendgrid etc): n/a

Error Message:

2022-07-11 17:53:35 [-][1][-][error][craft\db\MigrationManager::migrateUp] Failed to apply Install (time: 0.004s). Output:
    > create table {{%emails}} ...Exception: SQLSTATE[42000]: Syntax error or access violation: 1101 BLOB, TEXT, GEOMETRY or JSON column 'instructions' can't have a default value
The SQL being executed was: CREATE TABLE `con_emails` (
	`id` int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`key` varchar(255) NOT NULL,
	`template` varchar(255),
	`system` tinyint(1) DEFAULT FALSE,
	`redactorConfig` varchar(255),
	`heading` varchar(255) NOT NULL,
	`instructions` text DEFAULT '',
	`from` varchar(255),
	`fromName` varchar(255),
	`replyTo` varchar(255),
	`bcc` varchar(255),
	`cc` varchar(255),
	`plain` tinyint(1) DEFAULT FALSE,
	`saveLogs` tinyint(1),
	`sent` int(11) DEFAULT 0,
	`dateCreated` datetime(0) NOT NULL,
	`dateUpdated` datetime(0) NOT NULL,
	`uid` char(36) NOT NULL DEFAULT '0'
) ENGINE = InnoDb DEFAULT CHARACTER SET = utf8 DEFAULT COLLATE = utf8_unicode_ci (C:\wamp\craft\vendor\yiisoft\yii2\db\Schema.php:676)
#0 C:\wamp\craft\vendor\yiisoft\yii2\db\Command.php(1307): yii\db\Schema->convertException(Object(PDOException), 'CREATE TABLE `c...')
#1 C:\wamp\craft\vendor\yiisoft\yii2\db\Command.php(1102): yii\db\Command->internalExecute('CREATE TABLE `c...')
#2 C:\wamp\craft\vendor\yiisoft\yii2\db\Migration.php(323): yii\db\Command->execute()
#3 C:\wamp\craft\vendor\ryssbowh\craft-emails\src\migrations\Install.php(36): yii\db\Migration->createTable('{{%emails}}', Array)
#4 C:\wamp\craft\vendor\craftcms\cms\src\db\Migration.php(53): Ryssbowh\CraftEmails\migrations\Install->safeUp()
#5 C:\wamp\craft\vendor\craftcms\cms\src\db\MigrationManager.php(232): craft\db\Migration->up(true)
#6 C:\wamp\craft\vendor\craftcms\cms\src\base\Plugin.php(140): craft\db\MigrationManager->migrateUp(Object(Ryssbowh\CraftEmails\migrations\Install))
#7 C:\wamp\craft\vendor\craftcms\cms\src\services\Plugins.php(536): craft\base\Plugin->install()
#8 C:\wamp\craft\vendor\craftcms\cms\src\controllers\PluginsController.php(49): craft\services\Plugins->installPlugin('emails', 'standard')
#9 [internal function]: craft\controllers\PluginsController->actionInstallPlugin()
#10 C:\wamp\craft\vendor\yiisoft\yii2\base\InlineAction.php(57): call_user_func_array(Array, Array)
#11 C:\wamp\craft\vendor\yiisoft\yii2\base\Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#12 C:\wamp\craft\vendor\yiisoft\yii2\base\Module.php(552): yii\base\Controller->runAction('install-plugin', Array)
#13 C:\wamp\craft\vendor\craftcms\cms\src\web\Application.php(293): yii\base\Module->runAction('plugins/install...', Array)
#14 C:\wamp\craft\vendor\craftcms\cms\src\web\Application.php(602): craft\web\Application->runAction('plugins/install...', Array)
#15 C:\wamp\craft\vendor\craftcms\cms\src\web\Application.php(272): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#16 C:\wamp\craft\vendor\yiisoft\yii2\base\Application.php(384): craft\web\Application->handleRequest(Object(craft\web\Request))
#17 C:\wamp\craftweb\index.php(12): yii\base\Application->run()

**Comment by ryssbowh** [comment]
Thanks for reporting, what database do you use and in which version ?

Edit : This should be fixed in 1.4.2
