### ISSUE TITLE
Get recipients, subject and mail content from any section

### ISSUE THREAD

**Issue by mprofitlich** [ryssbowh/craft-emails#6]
**Is your feature request related to a problem? Please describe.**
For forms I prefer to use Craft’s built in form function without plugins. I can built any kind of form that way and save to any section. The plugin ‹Triggers› allows to trigger the E-Mails plugin. There however I can only choose recipients and mail content manually (users from Craft users or from Mailchimp). I cannot choose recipients and content based on the entry created (or any other section).

**Describe the solution you'd like**
I would like to have fields in the shot that allow Twig for loading recipients, subject and mail content from any section(s).

**Describe alternatives you've considered**
It might be possible using ‹Define more sources› but I cannot assess whether that’s the case.

**Comment by ryssbowh** [comment]
I don't quite understand :

You can define a source to fetch recipients from anywhere you like.

`Changing the content based on the entry created ?` Not sure what this means, can you expand please.

`I would like to have fields in the shot that allow Twig for loading recipients, subject and mail content from any section(s).`

How are sections related to email content or subject ?

**Comment by mprofitlich** [comment]
Thanks for your quick reply and question.

`Changing the content based on the entry created?` I use your trigger plugin to send an e-mail after an entry in a section got created. I want to then pull that entry’s content into the e-mail to be send. I helped myself now by querying the entry created last. Better would be if the trigger could pass the created entry’s id to the e-mail plugin so that it surely uses that entry. That’s acombined trigger and mail plugin issue.

`I would like to have fields in the shot that allow Twig for loading recipients`~, subject and mail content~ `from any section(s).` Subject and content I managed (only the issue above stays). The recipients issue is one for the trigger plugin, I realised.

**Comment by ryssbowh** [comment]
On your first point : The data from the trigger is passed to the email so you have the following variables defined already :
- entry
- event
- isNew
and available to use anywhere in your email (subject, content)

On your second point, I assume you want to load your own emails as recipients ? Then you need to define a source :
```
class MyEmailSource extends Component implements EmailSourceInterface
{
    public function getName(): string
    {
        return \Craft::t('emails', 'My source');
    }

    public function getHandle(): string
    {
        return 'my_source';
    }

    public function getEmails(): array
    {
        $emails = [];
        foreach (User::find()->all() as $user) {
            $emails[$user->email] = $user->friendlyName;
        }
        return $emails;
    }
}

Event::on(
    EmailSourceService::class,
    EmailSourceService::EVENT_REGISTER,
    function (RegisterEmailSourcesEvent $e) {
        $e->add(new MyEmailSource);
    }
);
```

**Comment by mprofitlich** [comment]
Thank you for your detailed reply, I appreciate it. I am now successfully using ‹entry› in my e-mail content. And I now understand that the data made available by the trigger is well documented in the trigger plugin. Sorry for not having seen it – I am new to Craft.

Yes, I want to load my own source of e-mail addresses. Thank you for the code for a source. I now understand I have to write a module or plugin.
