### ISSUE TITLE
Ajax form submit gets HTTP 500 error when an email is sent

### ISSUE THREAD

**Issue by mprofitlich** [ryssbowh/craft-emails#7]
**Describe the bug**
I use the email plugin in combination with the trigger plugin. When a visitor sends a form, a save entry trigger triggers an email. The form is sent by Ajax. This works: The data is saved to an entry, the trigger triggers, the mail is sent. This does not work: The HTTP response is 500 (error). Screenshot from developer toolbar (network tab) attached. It’s not the trigger, I tested with a log trigger instead of email and no error occurs.

<img width="564" alt="Bildschirmfoto 2022-09-23 um 16 57 40" src="https://user-images.githubusercontent.com/6146601/192017034-e755c6f2-7be1-4ed0-b86c-a4d13ae776ef.png">

**To Reproduce**
1. Create a frontend form that saves to a section
2. Create a trigger that listens to the section when an entry is saved
3. Create an email that is triggered by the trigger
4. Send the frontend form by Ajax
5. Read the HTTP response

**Software:**
 - Emails version: 2.0.2
 - Craft version: 4.2.5.1
 - Email adaptor (sendgrid etc): SMTP via Craft

**Comment by ryssbowh** [comment]
Thanks for reporting, this is fixed in 2.0.3
