### ISSUE TITLE
E-Mail body starts with empty lines and spaces

### ISSUE THREAD

**Issue by mprofitlich** [ryssbowh/craft-emails#8]
**Describe the bug**
E-mails sent by the plugin start with two empty lines and then seven spaces.

**To Reproduce**
1. Create a text-only e-mail
2. Start your e-mail body content with a twig variable
3. Send an e-mail

**Software:**
 - Emails version: 2.0.3
 - Craft version: 4.2.5.1
 - Email adaptor (sendgrid etc): SMTP via Craft

**Comment by ryssbowh** [comment]
Hi,

I fixed this in 2.0.4
