### ISSUE TITLE
Can't view logs within Craft Admin Panel

### ISSUE THREAD

**Issue by mitchellgemma** [ryssbowh/craft-emails#9]
**Describe the bug**
I click on the email, click actions, and then click logs, and then 'view more' under actions - which then pops up an error message with no description

**To Reproduce**
1. Setup and email and an email shot (I've made sure save logs is enabled)
2. Send an email using the email shot - email sends fine
3. Check logs in Craft - this is when error message pops up
4. Logs within the code in storage/logs/emails shows up

**Software:**
 - Emails version: 2.0.6
 - Craft version: 4.3.8.2
 - Email adaptor (sendgrid etc): None

**Comment by ryssbowh** [comment]
Hi,
Do you have the screenshot or content of that error message ? I can't reproduce this. The error shows up when you click on "View more" instead of the popup ?
Which email adaptor are you using ? SMTP, Gmail etc ?

**Comment by mitchellgemma** [comment]
Thanks for the quick response! We are using SMTP for our email adaptor. In the bottom left you will see the message that just says 'error'. It's triggered after clicking "view more".

<img width="1509" alt="email_error_message" src="https://user-images.githubusercontent.com/107566585/218771378-d85e2802-969b-489b-92c9-2c15cb7646c9.png">

**Comment by ryssbowh** [comment]
Ok, could you send me your log file please (storage/logs/web-****-**-**.log) at support@puzzlers.run ?

**Comment by ryssbowh** [comment]
Thanks for that, I could replicate and fixed it in 2.0.7

**Comment by mitchellgemma** [comment]
Thanks so much! I just tested it and the logs are working for me now.

Thanks again!


*-*
*  Mitch Gemma / **Bonfire Studios*
  e.  ***@***.***
  w.  hellobonfire.com
